
primitives:
  trigger:
    type: base
    input_ports: 
      trigger: bool
    output_ports: 
      status: bool
  move2pose:
    type: trajectory
    input_ports: 
      pose: Pose
    output_ports: 
      status: bool
  Move:
    type: trajectory
    input_ports: 
      from: Pose
      to: Pose
    output_ports: 
      status: bool
  Pick:
    type: trajectory
    input_ports: 
      above: Pose
      at: Pose
    output_ports: 
      status: bool
  Place:
    type: trajectory
    input_ports: 
      above: Pose
      at: Pose
    output_ports: 
      status: bool